"""add order cancellation reasons

Revision ID: 8ee3461efbbf
Revises: 4365df00046b
Create Date: 2026-09-21 14:31:22.646651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee3461efbbf'
down_revision: Union[str, None] = '4365df00046b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancellation_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Orders cancelled before reasons were tracked: say so honestly rather
    # than inventing one, and keep the best timestamp we have.
    op.execute(
        "UPDATE orders SET cancellation_reason = 'Reason not recorded', cancelled_at = updated_at "
        "WHERE status = 'cancelled'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'cancelled_by')
    op.drop_column('orders', 'cancellation_reason')
    # ### end Alembic commands ###
