"""add delivery_pin to deliveries

Revision ID: 9d22faa0a76c
Revises: b74975c4966a
Create Date: 2026-09-17 15:53:39.907806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d22faa0a76c'
down_revision: Union[str, None] = 'b74975c4966a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('delivery_pin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'delivery_pin')
    # ### end Alembic commands ###
