"""add payment fields to order

Revision ID: a7b255c5d8b1
Revises: 45eb546e3ad4
Create Date: 2026-04-23 11:41:22.040578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b255c5d8b1'
down_revision: Union[str, None] = '45eb546e3ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_reference', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_gateway_response', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_payment_reference'), 'orders', ['payment_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_payment_reference'), table_name='orders')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'payment_gateway_response')
    op.drop_column('orders', 'payment_reference')
    # ### end Alembic commands ###
