"""add courier fields to deliveries

Revision ID: b74975c4966a
Revises: b1c3d5e7f9a2
Create Date: 2026-09-17 14:33:03.239023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74975c4966a'
down_revision: Union[str, None] = 'b1c3d5e7f9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('courier_name', sa.String(), nullable=True))
    op.add_column('deliveries', sa.Column('courier_phone', sa.String(), nullable=True))
    op.add_column('deliveries', sa.Column('courier_service', sa.String(), nullable=True))
    op.add_column('deliveries', sa.Column('courier_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'courier_reference')
    op.drop_column('deliveries', 'courier_service')
    op.drop_column('deliveries', 'courier_phone')
    op.drop_column('deliveries', 'courier_name')
    # ### end Alembic commands ###
