"""add push subscriptions and notification push tracking

Revision ID: d191a422460e
Revises: a2c8e4f6b9d1
Create Date: 2026-09-30 08:17:36.145834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd191a422460e'
down_revision: Union[str, None] = 'a2c8e4f6b9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.add_column('admin_notifications', sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_admin_notifications_pushed_at'), 'admin_notifications', ['pushed_at'], unique=False)
    # ### end Alembic commands ###

    # Notifications that already existed before push shipped shouldn't all
    # fire off in one flood the moment the delivery sweep first runs.
    op.execute("UPDATE admin_notifications SET pushed_at = created_at WHERE pushed_at IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_notifications_pushed_at'), table_name='admin_notifications')
    op.drop_column('admin_notifications', 'pushed_at')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
